######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 10 21:19:30 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h resynthesizer.h utils.h
SOURCES += main.cpp window.cpp resynthesizer.cpp

QMAKE_CXXFLAGS += -g -std=c++0x
